"""initial schema

Revision ID: 0d9844ecf863
Revises: 
Create Date: 2026-10-02 15:25:41.860086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d9844ecf863'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_dialog_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('level', sa.Enum('NORMAL', 'MILD', 'MODERATE', 'SEVERE', name='crisislevel'), nullable=False),
    sa.Column('keywords_matched', sa.String(length=200), nullable=True),
    sa.Column('raw_snippet', sa.Text(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('intervention_type', sa.Enum('TALK', 'PARENT_MEETING', 'PSYCHOLOGY_REFERRAL', 'OTHER', name='interventiontype'), nullable=True),
    sa.Column('intervention_note', sa.Text(), nullable=True),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('follow_up_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_dialog_summaries_student_id'), 'ai_dialog_summaries', ['student_id'], unique=False)
    op.create_table('announcement_reads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('announcement_id', sa.Integer(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'announcement_id', name='uq_student_announcement')
    )
    op.create_index(op.f('ix_announcement_reads_announcement_id'), 'announcement_reads', ['announcement_id'], unique=False)
    op.create_index(op.f('ix_announcement_reads_student_id'), 'announcement_reads', ['student_id'], unique=False)
    op.create_table('campus_impression_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('college_key', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('date', sa.String(length=20), nullable=True),
    sa.Column('fetched_at', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campus_impression_items_college_key'), 'campus_impression_items', ['college_key'], unique=False)
    op.create_index(op.f('ix_campus_impression_items_source'), 'campus_impression_items', ['source'], unique=False)
    op.create_table('campus_sceneries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('area', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('certificates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('competition_name', sa.String(length=200), nullable=True),
    sa.Column('award_level', sa.Enum('SCHOOL', 'CITY', 'PROVINCE', 'NATIONAL', 'INTERNATIONAL', name='awardlevel'), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='certstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_certificates_student_id'), 'certificates', ['student_id'], unique=False)
    op.create_table('colleges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False, comment='学院代码，如 SE'),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('community_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.Column('comment_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_community_posts_category'), 'community_posts', ['category'], unique=False)
    op.create_index(op.f('ix_community_posts_student_id'), 'community_posts', ['student_id'], unique=False)
    op.create_table('conversation_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('key_insights', sa.JSON(), nullable=True),
    sa.Column('topics', sa.JSON(), nullable=True),
    sa.Column('sentiment', sa.String(length=20), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_summaries_conversation_id'), 'conversation_summaries', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_conversation_summaries_student_id'), 'conversation_summaries', ['student_id'], unique=False)
    op.create_table('emotion_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('emotion', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=True),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emotion_records_user_id'), 'emotion_records', ['user_id'], unique=False)
    op.create_table('exams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('course_name', sa.String(length=100), nullable=False),
    sa.Column('exam_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exams_student_id'), 'exams', ['student_id'], unique=False)
    op.create_table('external_feed_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False, comment='papers/agents/opensource/news'),
    sa.Column('feed_key', sa.String(length=50), nullable=False, comment='来源标识 arxiv/github-stars/gitee/...'),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('link', sa.String(length=700), nullable=False),
    sa.Column('author', sa.String(length=200), nullable=True, comment='论文作者或仓库全名'),
    sa.Column('source_name', sa.String(length=100), nullable=True, comment='展示用来源名'),
    sa.Column('is_highlight', sa.Boolean(), nullable=False, comment='热点/置顶标记'),
    sa.Column('meta', sa.JSON(), nullable=True, comment='排行指标等额外信息'),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('link', name='uq_feed_link')
    )
    op.create_index(op.f('ix_external_feed_items_feed_key'), 'external_feed_items', ['feed_key'], unique=False)
    op.create_index(op.f('ix_external_feed_items_source_type'), 'external_feed_items', ['source_type'], unique=False)
    op.create_table('feed_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='来源名称'),
    sa.Column('kind', sa.String(length=20), nullable=False, comment='rss/html/arxiv/github/gitee/lmarena'),
    sa.Column('source_type', sa.String(length=20), nullable=False, comment='归属分类'),
    sa.Column('feed_key', sa.String(length=50), nullable=True, comment='去重标识(可空自动生成)'),
    sa.Column('url', sa.String(length=700), nullable=False),
    sa.Column('query', sa.String(length=500), nullable=True, comment='API 类源的查询参数'),
    sa.Column('base_url', sa.String(length=300), nullable=True, comment='html 相对链接基础'),
    sa.Column('filter_kw', sa.JSON(), nullable=True, comment='标题关键词过滤'),
    sa.Column('date_only', sa.Boolean(), nullable=False, comment='仅保留标题含日期的条目'),
    sa.Column('per_page', sa.Integer(), nullable=False),
    sa.Column('is_builtin', sa.Boolean(), nullable=False, comment='内置预设源，不可删除'),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feed_sources_enabled'), 'feed_sources', ['enabled'], unique=False)
    op.create_index(op.f('ix_feed_sources_source_type'), 'feed_sources', ['source_type'], unique=False)
    op.create_table('grades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('course_name', sa.String(length=100), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('credit', sa.Float(), nullable=False),
    sa.Column('gpa', sa.Float(), nullable=False),
    sa.Column('semester', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grades_student_id'), 'grades', ['student_id'], unique=False)
    op.create_table('growth_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('goal_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False, comment='长期目标描述'),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'PAUSED', name='goalstatus'), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False, comment='0-100'),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_growth_goals_student_id'), 'growth_goals', ['student_id'], unique=False)
    op.create_table('growth_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('HONOR', 'COMPETITION', 'PRACTICE', 'PAPER', 'ACHIEVEMENT', name='recordtype'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('attachment_url', sa.String(length=255), nullable=True),
    sa.Column('honor_level', sa.String(length=20), nullable=True),
    sa.Column('organizer', sa.String(length=200), nullable=True),
    sa.Column('competition_level', sa.String(length=100), nullable=True),
    sa.Column('practice_type', sa.String(length=100), nullable=True),
    sa.Column('practice_certificate', sa.Text(), nullable=True),
    sa.Column('paper_type', sa.String(length=50), nullable=True),
    sa.Column('paper_name', sa.String(length=300), nullable=True),
    sa.Column('first_author', sa.String(length=100), nullable=True),
    sa.Column('second_author', sa.String(length=100), nullable=True),
    sa.Column('third_author', sa.String(length=100), nullable=True),
    sa.Column('achievement_type', sa.String(length=50), nullable=True),
    sa.Column('achievement_name', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_growth_records_student_id'), 'growth_records', ['student_id'], unique=False)
    op.create_table('knowledge_base',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('question', sa.String(length=500), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('tags', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_base_category'), 'knowledge_base', ['category'], unique=False)
    op.create_table('leave_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('leave_type', sa.Enum('COMPETITION', 'SICK', 'PERSONAL', 'OTHER', name='leavetype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='leavestatus'), nullable=False),
    sa.Column('tutor_id', sa.Integer(), nullable=True),
    sa.Column('reject_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leave_requests_student_id'), 'leave_requests', ['student_id'], unique=False)
    op.create_table('resource_favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(length=20), nullable=False, comment='knowledge/announcement/community'),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'item_type', 'item_id', name='uq_user_item')
    )
    op.create_index(op.f('ix_resource_favorites_user_id'), 'resource_favorites', ['user_id'], unique=False)
    op.create_table('semesters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=20), nullable=False, comment='学期值，如 2025-2026-2'),
    sa.Column('label', sa.String(length=50), nullable=False, comment='显示名称，如 2025-2026 第二学期'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('value')
    )
    op.create_table('service_tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('applicant_id', sa.Integer(), nullable=False),
    sa.Column('applicant_name', sa.String(length=50), nullable=False),
    sa.Column('applicant_no', sa.String(length=50), nullable=False),
    sa.Column('applicant_college', sa.String(length=100), nullable=False),
    sa.Column('type', sa.Enum('LEAVE', 'CERTIFICATE', 'PROJECT', name='tickettype'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('attachment', sa.String(length=255), nullable=True),
    sa.Column('form_data', sa.JSON(), nullable=True),
    sa.Column('attachments', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='ticketstatus'), nullable=False),
    sa.Column('approver_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_tickets_applicant_id'), 'service_tickets', ['applicant_id'], unique=False)
    op.create_table('sms_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('receiver_phone', sa.String(length=30), nullable=True),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('template', sa.String(length=200), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sms_logs_receiver_phone'), 'sms_logs', ['receiver_phone'], unique=False)
    op.create_index(op.f('ix_sms_logs_user_id'), 'sms_logs', ['user_id'], unique=False)
    op.create_table('student_profile_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('academic_score', sa.Float(), nullable=False),
    sa.Column('psychological_risk', sa.Float(), nullable=False),
    sa.Column('engagement_score', sa.Float(), nullable=False),
    sa.Column('growth_score', sa.Float(), nullable=False),
    sa.Column('overall_risk', sa.Float(), nullable=False),
    sa.Column('behavioral_patterns', sa.JSON(), nullable=True),
    sa.Column('key_insights', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_profile_snapshots_snapshot_date'), 'student_profile_snapshots', ['snapshot_date'], unique=False)
    op.create_index(op.f('ix_student_profile_snapshots_student_id'), 'student_profile_snapshots', ['student_id'], unique=False)
    op.create_table('student_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(length=200), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_team', sa.Boolean(), nullable=False),
    sa.Column('team_members', sa.String(length=500), nullable=True),
    sa.Column('attachment_url', sa.String(length=255), nullable=True),
    sa.Column('tech_stack', sa.String(length=500), nullable=True, comment='技术栈'),
    sa.Column('my_role', sa.String(length=200), nullable=True, comment='我的角色'),
    sa.Column('project_link', sa.String(length=500), nullable=True, comment='项目链接'),
    sa.Column('description', sa.Text(), nullable=True, comment='项目描述'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_projects_student_id'), 'student_projects', ['student_id'], unique=False)
    op.create_table('student_resumes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('is_current', sa.Integer(), nullable=False, comment='当前简历标记 1/0'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_resumes_student_id'), 'student_resumes', ['student_id'], unique=False)
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_settings_id'), 'system_settings', ['id'], unique=False)
    op.create_index(op.f('ix_system_settings_key'), 'system_settings', ['key'], unique=True)
    op.create_table('teacher_announcements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('urgency', sa.Enum('NORMAL', 'IMPORTANT', 'URGENT', name='urgencylevel'), nullable=False),
    sa.Column('attachment_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teacher_announcements_teacher_id'), 'teacher_announcements', ['teacher_id'], unique=False)
    op.create_table('teacher_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('content', sa.String(length=500), nullable=False),
    sa.Column('urgency', sa.Enum('NORMAL', 'IMPORTANT', 'URGENT', name='urgencylevel'), server_default=sa.text("'NORMAL'"), nullable=False),
    sa.Column('completed', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teacher_schedules_date'), 'teacher_schedules', ['date'], unique=False)
    op.create_index(op.f('ix_teacher_schedules_teacher_id'), 'teacher_schedules', ['teacher_id'], unique=False)
    op.create_table('community_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['community_posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_community_comments_post_id'), 'community_comments', ['post_id'], unique=False)
    op.create_index(op.f('ix_community_comments_student_id'), 'community_comments', ['student_id'], unique=False)
    op.create_table('community_likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['community_posts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'student_id', name='uq_post_student')
    )
    op.create_index(op.f('ix_community_likes_post_id'), 'community_likes', ['post_id'], unique=False)
    op.create_index(op.f('ix_community_likes_student_id'), 'community_likes', ['student_id'], unique=False)
    op.create_table('majors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('college_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False, comment='专业代码'),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('college_id', 'code')
    )
    op.create_index(op.f('ix_majors_college_id'), 'majors', ['college_id'], unique=False)
    op.create_table('study_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=True, comment='关联长期目标'),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('objective', sa.Text(), nullable=True, comment='计划目标描述'),
    sa.Column('stage', sa.String(length=100), nullable=True, comment='当前阶段/周期描述'),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', name='planstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['growth_goals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_plans_student_id'), 'study_plans', ['student_id'], unique=False)
    op.create_table('class_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('major_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='班级名称，如 2024级软件工程1班'),
    sa.Column('grade', sa.Integer(), nullable=False, comment='入学年份'),
    sa.Column('student_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['major_id'], ['majors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('major_id', 'grade', 'name')
    )
    op.create_index(op.f('ix_class_groups_major_id'), 'class_groups', ['major_id'], unique=False)
    op.create_table('plan_stages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False, comment='阶段/关卡标题'),
    sa.Column('goal', sa.Text(), nullable=True, comment='阶段目标/里程碑说明'),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('LOCKED', 'ACTIVE', 'SUBMITTED', 'DONE', name='stagestatus'), nullable=False),
    sa.Column('ai_generated', sa.Boolean(), nullable=False, comment='是否 AI 自动拆解'),
    sa.Column('score', sa.Integer(), nullable=True, comment='AI 评估评分 0-100'),
    sa.Column('evaluation', sa.Text(), nullable=True, comment='AI 综合评估'),
    sa.Column('weaknesses', sa.Text(), nullable=True, comment='AI 指出的不足'),
    sa.Column('suggestions', sa.Text(), nullable=True, comment='AI 对后续任务的改进建议'),
    sa.Column('submitted_result', sa.Text(), nullable=True, comment='用户提交的阶段成果'),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['study_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_stages_plan_id'), 'plan_stages', ['plan_id'], unique=False)
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_group_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('teacher', sa.String(length=50), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False, comment='星期几 1-7'),
    sa.Column('start_period', sa.Integer(), nullable=False),
    sa.Column('end_period', sa.Integer(), nullable=False),
    sa.Column('week_start', sa.Integer(), nullable=False),
    sa.Column('week_end', sa.Integer(), nullable=False),
    sa.Column('semester', sa.String(length=20), nullable=False, comment='学期，如 2024-2025-1'),
    sa.Column('credit', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['class_group_id'], ['class_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courses_class_group_id'), 'courses', ['class_group_id'], unique=False)
    op.create_index('ix_courses_class_semester', 'courses', ['class_group_id', 'semester'], unique=False)
    op.create_table('plan_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('stage_id', sa.Integer(), nullable=True, comment='所属阶段(可空=通用任务)'),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('priority', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='taskpriority'), nullable=False),
    sa.Column('status', sa.Enum('TODO', 'DOING', 'DONE', name='taskstatus'), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['study_plans.id'], ),
    sa.ForeignKeyConstraint(['stage_id'], ['plan_stages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_tasks_plan_id'), 'plan_tasks', ['plan_id'], unique=False)
    op.create_index(op.f('ix_plan_tasks_stage_id'), 'plan_tasks', ['stage_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('role', sa.Enum('STUDENT', 'TEACHER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('college', sa.String(length=100), nullable=True),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('tutor_id', sa.Integer(), nullable=True),
    sa.Column('skills_json', sa.JSON(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('political_status', sa.String(length=20), nullable=True),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('hometown', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('class_name', sa.String(length=50), nullable=True, comment='班级'),
    sa.Column('class_group_id', sa.Integer(), nullable=True, comment='关联班级'),
    sa.Column('password_changed', sa.Boolean(), nullable=False, comment='是否已修改过密码'),
    sa.ForeignKeyConstraint(['class_group_id'], ['class_groups.id'], ),
    sa.ForeignKeyConstraint(['tutor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_class_group_id'), 'users', ['class_group_id'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_tutor_id'), 'users', ['tutor_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('type', sa.Enum('NORMAL', 'PROJECT', name='conversationtype'), nullable=False),
    sa.Column('project_template', sa.String(length=50), nullable=True),
    sa.Column('project_stage', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('BUG', 'FEATURE', 'COMPLAINT', 'OTHER', name='feedbacktype'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('contact', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'RESOLVED', 'REJECTED', name='feedbackstatus'), nullable=False),
    sa.Column('reply', sa.Text(), nullable=True),
    sa.Column('replied_by', sa.Integer(), nullable=True),
    sa.Column('replied_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['replied_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedbacks_id'), 'feedbacks', ['id'], unique=False)
    op.create_index(op.f('ix_feedbacks_status'), 'feedbacks', ['status'], unique=False)
    op.create_index(op.f('ix_feedbacks_user_id'), 'feedbacks', ['user_id'], unique=False)
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('avatar', sa.String(length=500), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('announcement', sa.Text(), nullable=True),
    sa.Column('is_dismissed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_groups_creator_id'), 'groups', ['creator_id'], unique=False)
    op.create_index(op.f('ix_groups_id'), 'groups', ['id'], unique=False)
    op.create_table('lost_found_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('contact', sa.String(length=200), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lost_found_items_user_id'), 'lost_found_items', ['user_id'], unique=False)
    op.create_table('material_archives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('category', sa.Enum('IDENTITY', 'STATEMENT', 'GRADE', 'REGISTER', 'OTHER', name='materialcategory'), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='materialstatus'), nullable=False),
    sa.Column('reject_reason', sa.String(length=500), nullable=True),
    sa.Column('reviewer_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_archives_student_id'), 'material_archives', ['student_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.create_index(op.f('ix_messages_receiver_id'), 'messages', ['receiver_id'], unique=False)
    op.create_index(op.f('ix_messages_sender_id'), 'messages', ['sender_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('type', sa.Enum('SYSTEM', 'APPROVAL', 'LEAVE', 'CRISIS', 'ANNOUNCEMENT', 'MESSAGE', 'FEEDBACK', name='notificationtype'), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('related_id', sa.Integer(), nullable=True),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('plan_checkins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('check_date', sa.Date(), nullable=False),
    sa.Column('minutes', sa.Integer(), nullable=False, comment='投入时长(分钟)'),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['study_plans.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['plan_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_checkins_check_date'), 'plan_checkins', ['check_date'], unique=False)
    op.create_index(op.f('ix_plan_checkins_plan_id'), 'plan_checkins', ['plan_id'], unique=False)
    op.create_index(op.f('ix_plan_checkins_student_id'), 'plan_checkins', ['student_id'], unique=False)
    op.create_table('conversation_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('thinking_content', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_messages_conversation_id'), 'conversation_messages', ['conversation_id'], unique=False)
    op.create_table('document_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('embedding_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('last_read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_members_group_id'), 'group_members', ['group_id'], unique=False)
    op.create_index(op.f('ix_group_members_id'), 'group_members', ['id'], unique=False)
    op.create_index(op.f('ix_group_members_user_id'), 'group_members', ['user_id'], unique=False)
    op.create_table('group_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_messages_group_id'), 'group_messages', ['group_id'], unique=False)
    op.create_index(op.f('ix_group_messages_id'), 'group_messages', ['id'], unique=False)
    op.create_index(op.f('ix_group_messages_sender_id'), 'group_messages', ['sender_id'], unique=False)
    op.create_table('lost_found_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['lost_found_items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lost_found_comments_item_id'), 'lost_found_comments', ['item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lost_found_comments_item_id'), table_name='lost_found_comments')
    op.drop_table('lost_found_comments')
    op.drop_index(op.f('ix_group_messages_sender_id'), table_name='group_messages')
    op.drop_index(op.f('ix_group_messages_id'), table_name='group_messages')
    op.drop_index(op.f('ix_group_messages_group_id'), table_name='group_messages')
    op.drop_table('group_messages')
    op.drop_index(op.f('ix_group_members_user_id'), table_name='group_members')
    op.drop_index(op.f('ix_group_members_id'), table_name='group_members')
    op.drop_index(op.f('ix_group_members_group_id'), table_name='group_members')
    op.drop_table('group_members')
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_conversation_messages_conversation_id'), table_name='conversation_messages')
    op.drop_table('conversation_messages')
    op.drop_index(op.f('ix_plan_checkins_student_id'), table_name='plan_checkins')
    op.drop_index(op.f('ix_plan_checkins_plan_id'), table_name='plan_checkins')
    op.drop_index(op.f('ix_plan_checkins_check_date'), table_name='plan_checkins')
    op.drop_table('plan_checkins')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_messages_sender_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_receiver_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_material_archives_student_id'), table_name='material_archives')
    op.drop_table('material_archives')
    op.drop_index(op.f('ix_lost_found_items_user_id'), table_name='lost_found_items')
    op.drop_table('lost_found_items')
    op.drop_index(op.f('ix_groups_id'), table_name='groups')
    op.drop_index(op.f('ix_groups_creator_id'), table_name='groups')
    op.drop_table('groups')
    op.drop_index(op.f('ix_feedbacks_user_id'), table_name='feedbacks')
    op.drop_index(op.f('ix_feedbacks_status'), table_name='feedbacks')
    op.drop_index(op.f('ix_feedbacks_id'), table_name='feedbacks')
    op.drop_table('feedbacks')
    op.drop_table('documents')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_tutor_id'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_class_group_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_plan_tasks_stage_id'), table_name='plan_tasks')
    op.drop_index(op.f('ix_plan_tasks_plan_id'), table_name='plan_tasks')
    op.drop_table('plan_tasks')
    op.drop_index('ix_courses_class_semester', table_name='courses')
    op.drop_index(op.f('ix_courses_class_group_id'), table_name='courses')
    op.drop_table('courses')
    op.drop_index(op.f('ix_plan_stages_plan_id'), table_name='plan_stages')
    op.drop_table('plan_stages')
    op.drop_index(op.f('ix_class_groups_major_id'), table_name='class_groups')
    op.drop_table('class_groups')
    op.drop_index(op.f('ix_study_plans_student_id'), table_name='study_plans')
    op.drop_table('study_plans')
    op.drop_index(op.f('ix_majors_college_id'), table_name='majors')
    op.drop_table('majors')
    op.drop_index(op.f('ix_community_likes_student_id'), table_name='community_likes')
    op.drop_index(op.f('ix_community_likes_post_id'), table_name='community_likes')
    op.drop_table('community_likes')
    op.drop_index(op.f('ix_community_comments_student_id'), table_name='community_comments')
    op.drop_index(op.f('ix_community_comments_post_id'), table_name='community_comments')
    op.drop_table('community_comments')
    op.drop_index(op.f('ix_teacher_schedules_teacher_id'), table_name='teacher_schedules')
    op.drop_index(op.f('ix_teacher_schedules_date'), table_name='teacher_schedules')
    op.drop_table('teacher_schedules')
    op.drop_index(op.f('ix_teacher_announcements_teacher_id'), table_name='teacher_announcements')
    op.drop_table('teacher_announcements')
    op.drop_index(op.f('ix_system_settings_key'), table_name='system_settings')
    op.drop_index(op.f('ix_system_settings_id'), table_name='system_settings')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_student_resumes_student_id'), table_name='student_resumes')
    op.drop_table('student_resumes')
    op.drop_index(op.f('ix_student_projects_student_id'), table_name='student_projects')
    op.drop_table('student_projects')
    op.drop_index(op.f('ix_student_profile_snapshots_student_id'), table_name='student_profile_snapshots')
    op.drop_index(op.f('ix_student_profile_snapshots_snapshot_date'), table_name='student_profile_snapshots')
    op.drop_table('student_profile_snapshots')
    op.drop_index(op.f('ix_sms_logs_user_id'), table_name='sms_logs')
    op.drop_index(op.f('ix_sms_logs_receiver_phone'), table_name='sms_logs')
    op.drop_table('sms_logs')
    op.drop_index(op.f('ix_service_tickets_applicant_id'), table_name='service_tickets')
    op.drop_table('service_tickets')
    op.drop_table('semesters')
    op.drop_index(op.f('ix_resource_favorites_user_id'), table_name='resource_favorites')
    op.drop_table('resource_favorites')
    op.drop_index(op.f('ix_leave_requests_student_id'), table_name='leave_requests')
    op.drop_table('leave_requests')
    op.drop_index(op.f('ix_knowledge_base_category'), table_name='knowledge_base')
    op.drop_table('knowledge_base')
    op.drop_index(op.f('ix_growth_records_student_id'), table_name='growth_records')
    op.drop_table('growth_records')
    op.drop_index(op.f('ix_growth_goals_student_id'), table_name='growth_goals')
    op.drop_table('growth_goals')
    op.drop_index(op.f('ix_grades_student_id'), table_name='grades')
    op.drop_table('grades')
    op.drop_index(op.f('ix_feed_sources_source_type'), table_name='feed_sources')
    op.drop_index(op.f('ix_feed_sources_enabled'), table_name='feed_sources')
    op.drop_table('feed_sources')
    op.drop_index(op.f('ix_external_feed_items_source_type'), table_name='external_feed_items')
    op.drop_index(op.f('ix_external_feed_items_feed_key'), table_name='external_feed_items')
    op.drop_table('external_feed_items')
    op.drop_index(op.f('ix_exams_student_id'), table_name='exams')
    op.drop_table('exams')
    op.drop_index(op.f('ix_emotion_records_user_id'), table_name='emotion_records')
    op.drop_table('emotion_records')
    op.drop_index(op.f('ix_conversation_summaries_student_id'), table_name='conversation_summaries')
    op.drop_index(op.f('ix_conversation_summaries_conversation_id'), table_name='conversation_summaries')
    op.drop_table('conversation_summaries')
    op.drop_index(op.f('ix_community_posts_student_id'), table_name='community_posts')
    op.drop_index(op.f('ix_community_posts_category'), table_name='community_posts')
    op.drop_table('community_posts')
    op.drop_table('colleges')
    op.drop_index(op.f('ix_certificates_student_id'), table_name='certificates')
    op.drop_table('certificates')
    op.drop_table('campus_sceneries')
    op.drop_index(op.f('ix_campus_impression_items_source'), table_name='campus_impression_items')
    op.drop_index(op.f('ix_campus_impression_items_college_key'), table_name='campus_impression_items')
    op.drop_table('campus_impression_items')
    op.drop_index(op.f('ix_announcement_reads_student_id'), table_name='announcement_reads')
    op.drop_index(op.f('ix_announcement_reads_announcement_id'), table_name='announcement_reads')
    op.drop_table('announcement_reads')
    op.drop_index(op.f('ix_ai_dialog_summaries_student_id'), table_name='ai_dialog_summaries')
    op.drop_table('ai_dialog_summaries')
    # ### end Alembic commands ###
