"""add campus_impression_items

Revision ID: ef8ceac9af06
Revises: f2db7e9a2220
Create Date: 2026-08-08 16:05:27.001386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef8ceac9af06'
down_revision: Union[str, Sequence[str], None] = 'f2db7e9a2220'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campus_impression_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('college_key', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('date', sa.String(length=20), nullable=True),
    sa.Column('fetched_at', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campus_impression_items_college_key'), 'campus_impression_items', ['college_key'], unique=False)
    op.create_index(op.f('ix_campus_impression_items_source'), 'campus_impression_items', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_campus_impression_items_source'), table_name='campus_impression_items')
    op.drop_index(op.f('ix_campus_impression_items_college_key'), table_name='campus_impression_items')
    op.drop_table('campus_impression_items')
    # ### end Alembic commands ###
